name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose

    # Run the tests not in parallel in order to prevent heisenbug
    # (bug that seems to disappear or alter its behavior when one
    # attempts to study it) in tests/optimizer/ir_constructor.rs
    - name: Run tests
      run: cargo test -- --test-threads 1
